MyProject/Models/IndividualButtonPartial.cs
using System;
using System.Text;

namespace MyProject.Models
{
    public class IndividualButtonPartial
    {
        public string ButtonType { get; set; }
        public string Action { get; set; }
        public string Glyph { get; set; }
        public string Text { get; set; }

        public int? MemberTypeId { get; set; }
        public string CustomerId { get; set; }

        public string ActionParameter
        {
            get
            {
                var param = new StringBuilder(@"/");
                if (MemberTypeId != 0 && MemberTypeId != null)
                {
                    param.Append(String.Format("{0}", MemberTypeId));
                }

                if (!string.IsNullOrEmpty(CustomerId))
                {
                    param.Append(String.Format("{0}", CustomerId));
                }

                return param.ToString().Substring(0, param.Length);
            } 
        }
    }
}

MyProject/Controllers/CardListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyProject.Models;
using Microsoft.AspNetCore.Mvc;
using MyProject.Data;

namespace MyProject.Controllers
{
    public class CardListsController : Controller
    {

        private readonly ApplicationDbContext _db;

        public CardListsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }


    }
}

MyProject/Controllers/MemberListsController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using MyProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyProject.Data;

namespace MyProject.Controllers
{
    public class MemberListsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MemberListsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string option = null, string search = null)
        {
            var users = _db.Users.ToList();

            if (option == "email" && search != null)
            {
                users = _db.Users.Where(m => m.Email.ToLower().Contains(search.ToLower())).ToList();
            }
            else
            {
                if (option == "name" && search != null)
                {
                    users = _db.Users.Where(m => m.FirstName.ToLower().Contains(search.ToLower())
                                                   || m.LastName.ToLower().Contains(search.ToLower())).ToList();
                }
                else
                {
                    if (option == "phone" && search != null)
                    {
                        users = _db.Users.Where(m => m.PhoneNumber.ToLower().Contains(search.ToLower())).ToList();
                    }
                   
                }
            }
            return View(users);
        }

        // GET: Detail
        public async Task<IActionResult> Detail(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _db.Users.SingleOrDefaultAsync(m => m.Id == id);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);

        }


        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _db.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser applicationUser)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", applicationUser);
            }
            else
            {
                var userInDb = _db.Users.SingleOrDefault(m => m.Id == applicationUser.Id);
                if (userInDb == null)
                {
                    return NotFound();
                }

                //_db.Users.Update(applicationUser);
                userInDb.FirstName = applicationUser.FirstName;
                userInDb.LastName = applicationUser.LastName;
                userInDb.Email = applicationUser.Email;
                userInDb.Address = applicationUser.Address;
                userInDb.City = applicationUser.City;
                userInDb.PostalCode = applicationUser.PostalCode;
                userInDb.PhoneNumber = applicationUser.PhoneNumber;
               
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ApplicationUser user = await _db.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveCustomer(string id)
        {
            var userinDb = await _db.Users.SingleOrDefaultAsync(m => m.Id == id);
            _db.Users.Remove(userinDb);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               _db.Dispose();
            }
        }
    }
}

MyProject/Controllers/MemberTypeListsController.cs
using System.Linq;
using System.Threading.Tasks;
using MyProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyProject.Data;

namespace MyProject.Controllers
{
    public class MemberTypeListsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public MemberTypeListsController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET: MemberTypeLists
        public IActionResult Index()
        {
            return View(_db.Membertypies.ToList());
        }

        // GET: MemberTypeLists/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MemberTypeLists memberTypeLists)
        {
            if (ModelState.IsValid)
            {
                _db.Add(memberTypeLists);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(memberTypeLists);
        }


        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberTypes = _db.Membertypies.SingleOrDefault(m => m.Id == id);
            if (memberTypes == null)
            {
                return NotFound();
            }

            return View(memberTypes);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MemberTypeLists memberTypeLists)
        {
            if (memberTypeLists.Id != id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(memberTypeLists);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(memberTypeLists);
        }


        public IActionResult Detail(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberTypes = _db.Membertypies.SingleOrDefault(m => m.Id == id);
            if (memberTypes == null)
            {
                return NotFound();
            }

            return View(memberTypes);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var memberTypes = _db.Membertypies.SingleOrDefault(m => m.Id == id);
            if (memberTypes == null)
            {
                return NotFound();
            }

            return View(memberTypes);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveMembertypes(MemberTypeLists memberTypeLists)
        {
            var deleteMemberTypes = await _db.Membertypies.SingleOrDefaultAsync(m => m.Id == memberTypeLists.Id);

            _db.Membertypies.Remove(deleteMemberTypes);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
               _db.Dispose();
            }
        }
    }
}

MyProject/Views/Shared/_IndividualButtonPartial.cshtml
@model IndividualButtonPartial

<a class="btn btn-sm @Model.ButtonType" href="@Url.Action(Model.Action)@Model.ActionParameter">

    <span class="glyphicon glyphicon-@Model.Glyph"></span>
    <span class="sr-only">@Model.Text</span>
</a>

MyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyProject</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="MemberLists" asp-action="Index">Member</a></li>
                    <li><a asp-area="" asp-controller="MemberTypeLists" asp-action="Index">Member Types</a></li>
                    <li><a asp-area="" asp-controller="CardLists" asp-action="Index">Cards</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - MyProject</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

MyProject/Views/Shared/_TableButtonPartial.cshtml
@model IndividualButtonPartial

<td style="width:150px;">
    <div class="btn-group" role="group">
        @Html.Partial("_IndividualButtonPartial",
            new IndividualButtonPartial
            {
                Action = "Edit",
                ButtonType = "btn-primary",
                Glyph = "pencil",
                Text = "Edit Button",
                MemberTypeId = Model.MemberTypeId,
                CustomerId = Model.CustomerId 
            })

        @Html.Partial("_IndividualButtonPartial",
            new IndividualButtonPartial
            {
                Action = "Detail",
                ButtonType = "btn-success",
                Glyph = "list",
                Text = "Detail Button",
                MemberTypeId = Model.MemberTypeId,
                CustomerId = Model.CustomerId
            })
        
        @Html.Partial("_IndividualButtonPartial",
            new IndividualButtonPartial
            {
                Action = "Delete",
                ButtonType = "btn-danger",
                Glyph = "trash",
                Text = "Delete Button",
                MemberTypeId = Model.MemberTypeId,
                CustomerId = Model.CustomerId
            })
    </div>
</td>